export const SET_SESSION_REQUEST = "SET_SESSION_REQUEST";
export const SET_SESSION_SUCCESS = "SET_SESSION_SUCCESS";
export const SET_SESSION_ERROR = "SET_SESSION_ERROR";

export const GET_SESSION_REQUEST = "GET_SESSION_REQUEST";
export const GET_SESSION_SUCCESS = "GET_SESSION_SUCCESS";
export const GET_SESSION_ERROR = "GET_SESSION_ERROR";

export const GET_USER_SESSIONS_REQUEST = "GET_USER_SESSIONS_REQUEST";
export const GET_USER_SESSIONS_SUCCESS = "GET_USER_SESSIONS_SUCCESS";
export const GET_USER_SESSIONS_ERROR = "GET_USER_SESSIONS_ERROR";

export const UPDATE_ACTIVE_SESSION = "UPDATE_ACTIVE_SESSION";

export const STOP_SESSION_REQUEST = "STOP_SESSION_REQUEST";
export const STOP_SESSION_SUCCESS = "STOP_SESSION_SUCCESS";
export const STOP_SESSION_ERROR = "STOP_SESSION_ERROR";

export const FINISH_SESSION_REQUEST = "FINISH_SESSION_REQUEST";
export const FINISH_SESSION_SUCCESS = "FINISH_SESSION_SUCCESS";
export const FINISH_SESSION_ERROR = "FINISH_SESSION_ERROR";

export const FINISH_CONGRATS_REQUEST = "FINISH_CONGRATS_REQUEST";
export const FINISH_CONGRATS_SUCCESS = "FINISH_CONGRATS_SUCCESS";
export const FINISH_CONGRATS_ERROR = "FINISH_CONGRATS_ERROR";

export const RESET_SESSION = "RESET_SESSION";
