export const SET_SESSION_REQUEST = "SET_SESSION_REQUEST";
export const SET_SESSION_SUCCESS = "SET_SESSION_SUCCESS";
export const SET_SESSION_ERROR = "SET_SESSION_ERROR";

export const GET_SESSION_REQUEST = "GET_SESSION_REQUEST";
export const GET_SESSION_SUCCESS = "GET_SESSION_SUCCESS";
export const GET_SESSION_ERROR = "GET_SESSION_ERROR";

export const GET_SESSIONS_REQUEST = "GET_SESSIONS_REQUEST";
export const GET_SESSIONS_SUCCESS = "GET_SESSIONS_SUCCESS";
export const GET_SESSIONS_ERROR = "GET_SESSIONS_ERROR";

export const UPDATE_ACTIVE_SESSION = "UPDATE_ACTIVE_SESSION";
